import Sidebar from '@/components/sidebar/Sidebar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar/Navbar'
import Login from './login/page'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase = createServerComponentClient({ cookies })

  const {
    data: { user },
  } = await supabase.auth.getUser()

  return (
    <html lang="en">
      <body className={inter.className}>
        {user ? (
          <>
            <div className="home">
              <Sidebar />
              <div className="homeContainer">
                <Navbar />
                {children}
              </div>
            </div>
          </>

        ) : (
          <div
            className="flex-row justify-center lg:px-96 items-center my-52  ">
            < Login />
          </div>
        )}

      </body>
    </html>
  )
}
